<?php
// This file generated by Propel 1.6.9 convert-conf target
// from XML runtime conf file /Users/thomas/Sites/unicycle-skill-tester/database/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'skilltester' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=skilltester',
        'user' => 'root',
        'password' => '',
        'settings' => 
        array (
          'charset' => 
          array (
            'value' => 'utf8',
          ),
        ),
      ),
    ),
    'default' => 'skilltester',
  ),
  'generator_version' => '1.6.9',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'propel-classmap.php');
return $conf;